package lp2;


import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * conversorUnidade.java
 *
 * Created on 01/03/2012, 00:45:06
 */
/**
 *
 * @author Caio Mariani de Oliveira
 */
public class conversorUnidade extends javax.swing.JFrame {

    /** Creates new form conversorUnidade */
    public conversorUnidade() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReal = new javax.swing.JLabel();
        converter = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        libra = new javax.swing.JRadioButton();
        euro = new javax.swing.JRadioButton();
        dolar = new javax.swing.JRadioButton();
        txtReal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReal.setText("valor Em Real");

        converter.setText("Converter");
        converter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        libra.setText("Libra");
        libra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraActionPerformed(evt);
            }
        });

        euro.setText("Euro");
        euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euroActionPerformed(evt);
            }
        });

        dolar.setText("Dolar");
        dolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolarActionPerformed(evt);
            }
        });

        jLabel1.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReal)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(euro)
                            .addComponent(libra)
                            .addComponent(dolar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(converter)
                        .addGap(18, 18, 18)
                        .addComponent(limpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtReal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblResultado)
                                .addComponent(jLabel1)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReal)
                    .addComponent(txtReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblResultado)
                .addGap(28, 28, 28)
                .addComponent(euro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(libra)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpar)
                            .addComponent(converter))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dolar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void converterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterActionPerformed
       if(txtReal.getText().isEmpty()){
          JOptionPane.showMessageDialog (null, "Digite um valor");
       }else{
        DecimalFormat x = new DecimalFormat("$ 000.00");
        double r = Double.parseDouble(txtReal.getText());
        if (dolar.isSelected() == true) {
            lblResultado.setText("Valor da conversão = " + x.format(r / 1.70));
        }
        if (euro.isSelected() == true) {
            lblResultado.setText("Valor da conversão = " + x.format(r / 2.36));
        }
        if (libra.isSelected() == true) {
            lblResultado.setText("Valor da conversão = " + x.format(r / 2.71));
        }
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_converterActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtReal.setText("");
        dolar.setSelected(false);
        euro.setSelected(false);
        libra.setSelected(false);
        lblResultado.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_limparActionPerformed

    private void euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euroActionPerformed
        dolar.setSelected(false);
        libra.setSelected(false);
    }//GEN-LAST:event_euroActionPerformed

    private void libraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraActionPerformed
        euro.setSelected(false);
        dolar.setSelected(false);       // TODO add your handling code here:
    }//GEN-LAST:event_libraActionPerformed

    private void dolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolarActionPerformed

        euro.setSelected(false);
        libra.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_dolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new conversorUnidade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton converter;
    private javax.swing.JRadioButton dolar;
    private javax.swing.JRadioButton euro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblReal;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton libra;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField txtReal;
    // End of variables declaration//GEN-END:variables
}
